#
#  Project Zomboid Dedicated Server using SteamCMD Docker Image.
#  Copyright (C) 2021-2022 Renegade-Master [renegade.master.dev@protonmail.com]
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: "3.8"

services:
  zomboid-dedicated-server:
    build:
      context: .
      dockerfile: docker/zomboid-dedicated-server.Dockerfile
    container_name: zomboid-dedicated-server
    restart: "no"
    environment:
      - "ADMIN_PASSWORD=changeme"
      - "ADMIN_USERNAME=pzuser"
      - "AUTOSAVE_INTERVAL=15"
      - "BIND_IP=0.0.0.0"
      - "DEFAULT_PORT=16261"
      - "GAME_VERSION=public"
      - "GC_CONFIG=ZGC"
      - "MAP_NAMES=Muldraugh, KY"
      - "MAX_PLAYERS=20"
      - "MAX_RAM=4096m"
      - "MOD_NAMES=autotsartrailers;tsarslib;BB_CommonSense;CraftHelperContinued;ExpandedHelicopterEvents;EasyConfigChucked;P4HasBeenRead;MapLegendUI;modoptions;ScrapWeapons(new version);TheWorkshop(new version);TheStar;simpleStatus;FRUsedCarsNLF;FRUsedCars;FRUsedCarsFT;FRUsedCarsNRN;BecomeDesensitized;TMC_TrueActions;ExtraMapSymbols;MapSymbolSizeSlider;ExtraMapSymbolsUI;SkillRecoveryJournal;ProximityInventory;RainWash;fuelsideindicator;KillCount"
      - "MOD_WORKSHOP_IDS=2282429356;2875848298;2787291513;2458631365;2544353492;2710167561;2169435993;2122265954;2619072426;2680473910;2867431511;1510950729;2627877543;2487022075;2734705913;2701170568;2503622437;2392709985;2529746725;2847184718;2657661246;2616986064;2553809727"
      - "PAUSE_ON_EMPTY=true"
      - "PUBLIC_SERVER=true"
      - "RCON_PASSWORD=changeme_rcon"
      - "RCON_PORT=27015"
      - "SERVER_NAME=GuardianTales"
      - "SERVER_PASSWORD=HoYeahLai"
      - "STEAM_VAC=true"
      - "UDP_PORT=16262"
      - "USE_STEAM=true"
      - "TZ=UTC"
    ports:
      - target: 16261
        published: 16261
        protocol: udp
      - target: 16262
        published: 16262
        protocol: udp
      - target: 27015
        published: 27015
        protocol: tcp
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ./ZomboidConfig:/home/steam/Zomboid/
